# Generated by Django 4.2.11 on 2025-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('APP', 'Appetizers'), ('MAIN', 'Main Menu'), ('DESS', 'Desserts'), ('DRINK', 'Drinks')], default='MAIN', max_length=10),
        ),
    ]
