# Generated by Django 4.2.11 on 2025-04-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_menu_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['category'], name='restaurant__categor_9098ce_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['name'], name='restaurant__name_681929_idx'),
        ),
    ]
